version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - IP_LIMIT=5
      - BLOCK_TIME=60
    depends_on:
      - redis